name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: 'zerosuxx/php-echo-server:latest'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and deploy docker image
        run: |
          docker pull ${{ env.IMAGE_NAME }} || true
          export VERSION=$(git describe --tags)
          echo $VERSION
          sed -i "s/d.e.v/$VERSION/g" bin/server
          docker buildx build \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --cache-from ${{ env.IMAGE_NAME }} \
            --platform linux/amd64,linux/arm64 \
            --push \
            --tag ${{ env.IMAGE_NAME }} \
            .
